import { LegalPage } from "@/app/(legal)/legal-page";

export const metadata = { title: "Terms of Service" };

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>
        This is a placeholder terms of service for ActProve. Before launch, have
        this reviewed by legal counsel.
      </p>
      <h2>Not legal advice</h2>
      <p>
        ActProve provides compliance operations tooling and informational
        content. It does not provide legal advice. Outputs generated by the
        platform should be reviewed by qualified professionals where appropriate.
      </p>
      <h2>Subscriptions</h2>
      <p>
        Plans are billed monthly or annually via Stripe. You may cancel at any
        time; access continues until the end of the billing period.
      </p>
    </LegalPage>
  );
}
