import "server-only";
import type { Browser } from "puppeteer-core";

const isServerless = Boolean(
  process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME,
);

/**
 * Launches headless Chrome. On Vercel/Lambda it uses @sparticuz/chromium (a
 * serverless-compatible binary); locally it uses an installed Chrome via
 * puppeteer-core's `channel`, or PUPPETEER_EXECUTABLE_PATH if set.
 */
async function launchBrowser(): Promise<Browser> {
  const puppeteer = (await import("puppeteer-core")).default;
  if (isServerless) {
    const chromium = (await import("@sparticuz/chromium")).default;
    return puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: true,
    });
  }
  const executablePath = process.env.PUPPETEER_EXECUTABLE_PATH;
  return puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
    ...(executablePath ? { executablePath } : { channel: "chrome" }),
  });
}

/** Renders an HTML string to a PDF buffer. */
export async function htmlToPdf(html: string): Promise<Buffer> {
  let browser: Browser | null = null;
  try {
    browser = await launchBrowser();
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "load" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", bottom: "24mm", left: "16mm", right: "16mm" },
      displayHeaderFooter: true,
      footerTemplate: `<div style="font-size:8px;color:#888;width:100%;text-align:center;">Generated by ActProve · actprove.com · <span class="date"></span> · Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>`,
      headerTemplate: `<div></div>`,
    });
    return Buffer.from(pdf);
  } finally {
    if (browser) await browser.close();
  }
}

const RISK_LABEL: Record<string, string> = {
  minimal_risk: "Minimal",
  limited_risk: "Limited",
  high_risk: "High Risk",
  prohibited: "Prohibited",
};
const RISK_COLOR: Record<string, string> = {
  minimal_risk: "#1D8348",
  limited_risk: "#D4AC0D",
  high_risk: "#E67E22",
  prohibited: "#C0392B",
};

interface RegisterSystem {
  name: string;
  vendor: string | null;
  useCase: string | null;
  riskTier: string | null;
  riskRationale: string | null;
  dataProcessed: string[];
  affectsPeople: boolean;
  humanOversight: boolean;
  logRetention: boolean;
  responsiblePerson: string | null;
  responsibleName: string | null;
  vendorCompliant: boolean | null;
  lastReviewedAt: Date | null;
  status: string;
}

interface RegisterOrg {
  name: string;
  country: string;
  logoUrl: string | null;
  plan: string;
}

const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"]/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] as string,
  );

/** Builds the audit-ready Living Register HTML (spec §6.5). */
export function registerHtml(
  org: RegisterOrg,
  systems: RegisterSystem[],
): string {
  const now = new Date().toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
  const counts = systems.reduce<Record<string, number>>((acc, s) => {
    const k = s.riskTier ?? "pending";
    acc[k] = (acc[k] ?? 0) + 1;
    return acc;
  }, {});

  const rows = systems
    .map(
      (s, i) => `
    <tr>
      <td>ORG-${String(i + 1).padStart(3, "0")}</td>
      <td><strong>${esc(s.name)}</strong></td>
      <td>${esc(s.vendor ?? "—")}</td>
      <td>${esc(s.useCase ?? "—")}</td>
      <td><span class="tier" style="background:${RISK_COLOR[s.riskTier ?? ""] ?? "#85929E"}">${RISK_LABEL[s.riskTier ?? ""] ?? "Pending"}</span></td>
      <td>${esc(s.dataProcessed.join(", ") || "—")}</td>
      <td>${s.affectsPeople ? "Yes" : "No"}</td>
      <td>${s.humanOversight ? "Yes" : "No"}</td>
      <td>${s.logRetention ? "Yes" : "No"}</td>
      <td>${esc(s.responsibleName ?? s.responsiblePerson ?? "—")}</td>
      <td>${s.vendorCompliant == null ? "?" : s.vendorCompliant ? "Yes" : "No"}</td>
      <td>${s.lastReviewedAt ? new Date(s.lastReviewedAt).toLocaleDateString("en-GB") : "Never"}</td>
    </tr>`,
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"><style>
    * { font-family: 'Helvetica Neue', Arial, sans-serif; box-sizing: border-box; }
    body { color: #1A252F; font-size: 11px; margin: 0; }
    .cover { page-break-after: always; padding: 60px 0; }
    .cover h1 { color: #1B4F72; font-size: 32px; margin: 0 0 8px; }
    .cover .sub { color: #555; font-size: 14px; }
    .badge { display:inline-block; background:#1B4F72; color:#fff; padding:4px 10px; border-radius:4px; font-size:11px; margin-top:24px; }
    h2 { color: #1B4F72; border-bottom: 2px solid #1B4F72; padding-bottom: 4px; font-size: 16px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background: #1B4F72; color: #fff; padding: 6px; text-align: left; font-size: 9px; }
    td { border: 1px solid #ddd; padding: 5px; font-size: 9px; vertical-align: top; }
    tr:nth-child(even) td { background: #F8F9FA; }
    .tier { color:#fff; padding:1px 6px; border-radius:8px; font-size:8px; white-space:nowrap; }
    .summary { display:flex; gap:16px; margin: 16px 0; }
    .summary div { background:#F2F3F4; border-radius:6px; padding:10px 16px; }
    .summary .n { font-size:20px; font-weight:bold; color:#1B4F72; }
    .appendix { page-break-before: always; }
    .appendix li { margin-bottom: 6px; }
  </style></head><body>
    <div class="cover">
      ${org.logoUrl ? `<img src="${esc(org.logoUrl)}" style="max-height:48px;margin-bottom:24px" />` : ""}
      <h1>EU AI Act — AI System Register</h1>
      <div class="sub">${esc(org.name)} · ${esc(org.country)}</div>
      <div class="sub">Generated ${now} · ${systems.length} registered AI systems</div>
      <div class="badge">Verified &amp; maintained with ActProve</div>
    </div>

    <h2>Register summary</h2>
    <div class="summary">
      <div><div class="n">${counts.minimal_risk ?? 0}</div>Minimal</div>
      <div><div class="n">${counts.limited_risk ?? 0}</div>Limited</div>
      <div><div class="n">${counts.high_risk ?? 0}</div>High risk</div>
      <div><div class="n">${counts.prohibited ?? 0}</div>Prohibited</div>
    </div>

    <h2>AI systems register</h2>
    <table>
      <thead><tr>
        <th>ID</th><th>System</th><th>Provider</th><th>Purpose (Art. 13)</th>
        <th>Risk (Art. 6)</th><th>Data (Art. 10)</th><th>Affects people (Art. 26)</th>
        <th>Oversight (Art. 14)</th><th>Logs (Art. 12)</th><th>Responsible (Art. 4)</th>
        <th>Vendor OK (Art. 26.7)</th><th>Reviewed</th>
      </tr></thead>
      <tbody>${rows || `<tr><td colspan="12">No systems registered.</td></tr>`}</tbody>
    </table>

    <div class="appendix">
      <h2>Appendix — EU AI Act quick reference</h2>
      <ul>
        <li><strong>Prohibited:</strong> banned practices (Art. 5) — must stop immediately.</li>
        <li><strong>High Risk:</strong> Annex III consequential decisions — risk management, documentation, human oversight, logging.</li>
        <li><strong>Limited Risk:</strong> transparency obligations (Art. 50) — disclose AI interaction.</li>
        <li><strong>Minimal Risk:</strong> no mandatory obligations; voluntary codes encouraged.</li>
      </ul>
      <p style="margin-top:24px;color:#888;font-size:9px;">This document is generated by ActProve and does not constitute legal advice.</p>
      <p style="margin-top:40px;">Signed off by: ____________________________ &nbsp;&nbsp; Date: ____________</p>
    </div>
  </body></html>`;
}
